services:
  db:
    image: postgres:15
    container_name: subscriptions-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscriptions_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: subscriptions-redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  pgdata:
